### ISSUE TITLE
Xác nhận các config trong build.yaml có cần thiết

### ISSUE THREAD

**Issue by tksvn-vanna** [TKSVN/constant_keys_generator#7]
Xác nhận các config dưới đây trong file `build.yaml` cái nào là thật sự cần thiết

```yaml
targets:
  $default:
    builders:
      locale_keys_builder:
        enabled: true
        generate_for:
          - lib/main.dart

builders:
    locale_keys_builder:
      import: "package:locale_keys_generator/locale_keys_generator.dart"
      builder_factories: ["localeKeysBuilder"]
      build_extensions: {r"$lib$": ["generated/locale_keys.dart"]}
      auto_apply: root_package
      build_to: source
```
